@startuml
autonumber

Subscriber -> InfoOperator: request for SportNewsChanel subscription
InfoOperator -> SportNewsChanel: request for register new observer
SportNewsChanel -> SportNewsChanel: addObserver(Subscriber)

Subscriber -> InfoOperator: request for NationalNewsChanel subscription
InfoOperator -> NationalNewsChanel: request for register new observer
NationalNewsChanel -> NationalNewsChanel: addObserver(Subscriber)

InfoOperator -> SportNewsChanel : creating News
NationalNewsChanel -> NationalNewsChanel : addNews(News)
NationalNewsChanel -> NationalNewsChanel: notifyObservers()
Subscriber -> Subscriber: updating list of news, notify Subscriber

@enduml